### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Erin59** [statisticianinstilettos/recmetrics#34]
Hi! Have been trying to install recmetrics with "pip install recmetrcis", keep getting an error "ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects". I'm using Windows, Python version 3.9.7, pip all upgraded. pip freeze shows that scikit-learn is actually already installed: "scikit-learn==0.24.2". I've also tried installing with pip from git, same result. Any ideas what I could still try?

**Comment by statisticianinstilettos** [comment]
Hey @Erin59 checking in. Did you get this resolved?

**Comment by anaklim** [comment]
> Hey @Erin59 checking in. Did you get this resolved?

Hi! It's still me, but another account. I don't think I've got it resolved - I've moved in the meantime from Windows to Mac M1, however, now I have another installation issue with M1:

```
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Looking in indexes: https://pypi.org/simple, https://anastasiia.klimashevskaia%40tv2.no:****@tv2norge.jfrog.io/tv2norge/api/pypi/ai-python-local/simple
Collecting recmetrics
  Using cached recmetrics-0.1.4.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: seaborn<0.12.0,>=0.11.0 in /opt/homebrew/lib/python3.9/site-packages (from recmetrics) (0.11.2)
Requirement already satisfied: pandas<2.0.0,>=1.1.3 in /opt/homebrew/lib/python3.9/site-packages (from recmetrics) (1.4.0)
Requirement already satisfied: scipy<2.0.0,>=1.5.2 in /opt/homebrew/lib/python3.9/site-packages (from recmetrics) (1.7.3)
Collecting ipython<8.0.0,>=7.18.1
  Downloading ipython-7.32.0-py3-none-any.whl (793 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 793.9/793.9 KB 7.3 MB/s eta 0:00:00
Collecting pytest-cov<3.0.0,>=2.10.1
  Downloading pytest_cov-2.12.1-py2.py3-none-any.whl (20 kB)
Collecting funcsigs<2.0.0,>=1.0.2
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Collecting plotly<5.0.0,>=4.11.0
  Using cached plotly-4.14.3-py2.py3-none-any.whl (13.2 MB)
Collecting scikit-learn<0.24.0,>=0.23.2
  Using cached scikit-learn-0.23.2.tar.gz (7.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [399 lines of output]
      Looking in indexes: https://pypi.org/simple, https://anastasiia.klimashevskaia%40tv2.no:****@tv2norge.jfrog.io/tv2norge/api/pypi/ai-python-local/simple, https://anastasiia.klimashevskaia%40tv2.no:****@tv2norge.jfrog.io/tv2norge/api/pypi/ai-python-local/simple
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX" and platform_python_implementation == "CPython"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX" and platform_python_implementation != "CPython"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting setuptools
        Using cached setuptools-62.1.0-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting Cython>=0.28.5
        Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting scipy>=0.19.1
        Using cached scipy-1.8.0-cp39-cp39-macosx_12_0_arm64.whl (28.7 MB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [159 lines of output]
            Running from numpy source directory.
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            blis_info:
            customize UnixCCompiler
              libraries blis not found in ['/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            openblas_info:
            customize UnixCCompiler
            customize UnixCCompiler
            customize UnixCCompiler
            customize UnixCCompiler
              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/opt/homebrew/opt/openblas/lib']
                language = c
                define_macros = [('HAVE_CBLAS', None)]
                runtime_library_dirs = ['/opt/homebrew/opt/openblas/lib']

              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/opt/homebrew/opt/openblas/lib']
                language = c
                define_macros = [('HAVE_CBLAS', None)]
                runtime_library_dirs = ['/opt/homebrew/opt/openblas/lib']

            /bin/sh: svnversion: command not found
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            openblas_lapack_info:
            customize UnixCCompiler
            customize UnixCCompiler
            customize UnixCCompiler
            C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -falign-functions=8 -I/opt/homebrew/opt/lapack/include

            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/var
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/var/folders
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/var/folders/gr
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta
            compile options: '-c'
            clang: /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/source.c
            clang /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/source.o -L/opt/homebrew/opt/openblas/lib -lopenblas -o /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmp420k4qta/a.out
            customize UnixCCompiler
            customize UnixCCompiler
              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/opt/homebrew/opt/openblas/lib']
                language = c
                define_macros = [('HAVE_CBLAS', None)]
                runtime_library_dirs = ['/opt/homebrew/opt/openblas/lib']

              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/opt/homebrew/opt/openblas/lib']
                language = c
                define_macros = [('HAVE_CBLAS', None)]
                runtime_library_dirs = ['/opt/homebrew/opt/openblas/lib']

            /opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            build_src
            building py_modules sources
            creating build
            creating build/src.macosx-12-arm64-3.9
            creating build/src.macosx-12-arm64-3.9/numpy
            creating build/src.macosx-12-arm64-3.9/numpy/distutils
            building library "npymath" sources
            get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
            customize Gnu95FCompiler
            Found executable /opt/homebrew/bin/gfortran
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/setup.py", line 443, in <module>
                setup_package()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/setup.py", line 435, in setup_package
                setup(**metadata)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/core.py", line 171, in setup
                return old_setup(**new_attr)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
                return distutils.core.setup(**attrs)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
                return run_commands(dist)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
                dist.run_commands()
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/opt/homebrew/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build.py", line 47, in run
                old_build.run(self)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build_src.py", line 142, in run
                self.build_sources()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build_src.py", line 153, in build_sources
                self.build_library_sources(*libname_info)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build_src.py", line 286, in build_library_sources
                sources = self.generate_sources(sources, (lib_name, build_info))
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build_src.py", line 369, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 667, in get_mathlib_info
                st = config_cmd.try_link('int main(void) { return 0;}')
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/config.py", line 241, in try_link
                self._check_compiler()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/config.py", line 82, in _check_compiler
                self.fcompiler = new_fcompiler(compiler=self.fcompiler,
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 884, in new_fcompiler
                compiler = get_default_fcompiler(plat, requiref90=requiref90,
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 855, in get_default_fcompiler
                compiler_type =  _find_existing_fcompiler(matching_compiler_types,
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 806, in _find_existing_fcompiler
                c.customize(dist)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 530, in customize
                linker_so_flags = self.flag_vars.linker_so
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/environment.py", line 40, in __getattr__
                return self._get_var(name, conf_desc)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/environment.py", line 56, in _get_var
                var = self._hook_handler(name, hook)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 709, in _environment_hook
                return hook()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/gnu.py", line 353, in get_flags_linker_so
                flags = GnuFCompiler.get_flags_linker_so(self)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/gnu.py", line 144, in get_flags_linker_so
                os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
              File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
                value = self.encodevalue(value)
              File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
                raise TypeError("str expected, not %s" % type(value).__name__)
            TypeError: str expected, not int
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error

        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.

            `setup.py clean` is not supported, use one of the following instead:

              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)

            Add `--force` to your command to use it anyway if you must (unsupported).

            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      Installing collected packages: wheel, setuptools, numpy, Cython, scipy
        Running setup.py install for numpy: started
        Running setup.py install for numpy: finished with status 'error'
        error: subprocess-exited-with-error

        × Running setup.py install for numpy did not run successfully.
        │ exit code: 1
        ╰─> [170 lines of output]
            Running from numpy source directory.

            Note: if you need reliable uninstall behavior, then install
            with pip instead of using `setup.py install`:

              - `pip install .`       (from a git repo or downloaded source
                                       release)
              - `pip install numpy`   (last NumPy release on PyPi)


            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            blis_info:
            customize UnixCCompiler
              libraries blis not found in ['/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            openblas_info:
            customize UnixCCompiler
            customize UnixCCompiler
            customize UnixCCompiler
            customize UnixCCompiler
              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/opt/homebrew/opt/openblas/lib']
                language = c
                define_macros = [('HAVE_CBLAS', None)]
                runtime_library_dirs = ['/opt/homebrew/opt/openblas/lib']

              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/opt/homebrew/opt/openblas/lib']
                language = c
                define_macros = [('HAVE_CBLAS', None)]
                runtime_library_dirs = ['/opt/homebrew/opt/openblas/lib']

            /bin/sh: svnversion: command not found
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE

            openblas_lapack_info:
            customize UnixCCompiler
            customize UnixCCompiler
            customize UnixCCompiler
            C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -falign-functions=8 -I/opt/homebrew/opt/lapack/include

            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/var
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/var/folders
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/var/folders/gr
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T
            creating /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp
            compile options: '-c'
            clang: /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/source.c
            clang /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/source.o -L/opt/homebrew/opt/openblas/lib -lopenblas -o /var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/tmpy2trx1dp/a.out
            customize UnixCCompiler
            customize UnixCCompiler
              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/opt/homebrew/opt/openblas/lib']
                language = c
                define_macros = [('HAVE_CBLAS', None)]
                runtime_library_dirs = ['/opt/homebrew/opt/openblas/lib']

              FOUND:
                libraries = ['openblas', 'openblas']
                library_dirs = ['/opt/homebrew/opt/openblas/lib']
                language = c
                define_macros = [('HAVE_CBLAS', None)]
                runtime_library_dirs = ['/opt/homebrew/opt/openblas/lib']

            /opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running install
            /opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running config_cc
            unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            build_src
            building py_modules sources
            building library "npymath" sources
            get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
            customize Gnu95FCompiler
            Found executable /opt/homebrew/bin/gfortran
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/setup.py", line 443, in <module>
                setup_package()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/setup.py", line 435, in setup_package
                setup(**metadata)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/core.py", line 171, in setup
                return old_setup(**new_attr)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
                return distutils.core.setup(**attrs)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
                return run_commands(dist)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
                dist.run_commands()
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/install.py", line 62, in run
                r = self.setuptools_run()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/install.py", line 36, in setuptools_run
                return distutils_install.run(self)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 670, in run
                self.run_command('build')
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build.py", line 47, in run
                old_build.run(self)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build_src.py", line 142, in run
                self.build_sources()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build_src.py", line 153, in build_sources
                self.build_library_sources(*libname_info)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build_src.py", line 286, in build_library_sources
                sources = self.generate_sources(sources, (lib_name, build_info))
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/build_src.py", line 369, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 667, in get_mathlib_info
                st = config_cmd.try_link('int main(void) { return 0;}')
              File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/config.py", line 241, in try_link
                self._check_compiler()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/command/config.py", line 82, in _check_compiler
                self.fcompiler = new_fcompiler(compiler=self.fcompiler,
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 884, in new_fcompiler
                compiler = get_default_fcompiler(plat, requiref90=requiref90,
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 855, in get_default_fcompiler
                compiler_type =  _find_existing_fcompiler(matching_compiler_types,
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 806, in _find_existing_fcompiler
                c.customize(dist)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 530, in customize
                linker_so_flags = self.flag_vars.linker_so
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/environment.py", line 40, in __getattr__
                return self._get_var(name, conf_desc)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/environment.py", line 56, in _get_var
                var = self._hook_handler(name, hook)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/__init__.py", line 709, in _environment_hook
                return hook()
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/gnu.py", line 353, in get_flags_linker_so
                flags = GnuFCompiler.get_flags_linker_so(self)
              File "/private/var/folders/gr/dpwnfzbj45sfzthq83r6cn7m0000gn/T/pip-install-ppnfg0r5/numpy_f5dd82b428b64b9aa1e66ee29d1d1b21/numpy/distutils/fcompiler/gnu.py", line 144, in get_flags_linker_so
                os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
              File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
                value = self.encodevalue(value)
              File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
                raise TypeError("str expected, not %s" % type(value).__name__)
            TypeError: str expected, not int
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      × Encountered error while trying to install package.
      ╰─> numpy

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

The weird thing here is that I already have numpy and Cython installed, but it seems like it's trying to install it new and fails and something wrong happens with cythonizing something. If you got any suggestions on what I could try - highly appreciated!

**Comment by anaklim** [comment]
Seems like it worked! Thank you a lot!

**Comment by anaklim** [comment]
I've seen the same issues for some other packages I've tried to install - is there anything else I could do against it myself in the future?

**Comment by Sanders003** [comment]
> Seems like it worked! Thank you a lot!

Can you tell me how you resolved it?

**Comment by anaklim** [comment]
> > Seems like it worked! Thank you a lot!
> 
> Can you tell me how you resolved it?

If I remember I don't think I did anything specific, the updated package mentioned above resolved the issue itself.
